from kivy.properties import StringProperty
from kivy.event import EventDispatcher

from Core.AppSettings import AppSettings
from Tools.BaseData import BaseData
from Tools.Singleton import Singleton

class AppText(BaseData, EventDispatcher, metaclass=Singleton):

    MainButtonBooks = StringProperty()
    MainButtonFindAMatch = StringProperty()
    MainButtonWords = StringProperty()
    MainButtonAddWord = StringProperty()
    MainButtonWordPuzzle = StringProperty()
    MainButtonCard = StringProperty()
    MainButtonCrossword = StringProperty()
    MainButtonTrCard = StringProperty()
    MainButtonSettings = StringProperty()
    MainBack = StringProperty()
    WordDetail = StringProperty()
    WordSave = StringProperty()
    WordEdit = StringProperty()
    WordExamples = StringProperty()
    Words = StringProperty()
    WordsAll = StringProperty()
    WordsWin = StringProperty()
    WordsFail = StringProperty()
    WordsSeries = StringProperty()
    WordsToLearned = StringProperty()
    WordsToIgnore = StringProperty()
    WordsToTraining = StringProperty()
    WordsNew = StringProperty()
    WordsTraining = StringProperty()
    WordsLearned = StringProperty()
    WordsIgnore = StringProperty()
    WordsAllWords = StringProperty()
    WordsRemove = StringProperty()
    BooksTitle = StringProperty()
    BooksAuthor = StringProperty()
    Crossword = StringProperty()
    CrosswordTips = StringProperty()
    CrosswordCheck = StringProperty()
    AddWord = StringProperty()
    AddTranscription = StringProperty()
    AddMeaning = StringProperty()
    GameHeader = StringProperty()
    GameNext = StringProperty()
    SettingTranslateTo = StringProperty()
    SettingTranslateFrom = StringProperty()
    SettingTranslatorSwitch = StringProperty()
    SettingPrincetonSwitch = StringProperty()
    AppLanguage = StringProperty()
    AppTheme = StringProperty()

    def __init__(self) -> None:
        super().__init__()
        self._filename = "apptext"
        self.Init()
        self.UpdateTexts()
    
    def GetLanguages(self):
        return list(self._data.keys())
    
    def UpdateTexts(self):
        self._currentLanguage = AppSettings().GetAppLanguage()
        self.MainButtonBooks = self._Get("main_button_books")
        self.MainButtonFindAMatch = self._Get("main_button_find_a_match")
        self.MainButtonWords = self._Get("main_button_words")
        self.MainButtonAddWord = self._Get("main_button_add_word")
        self.MainButtonWordPuzzle = self._Get("main_button_word_puzzle")
        self.MainButtonCard = self._Get("main_button_card")
        self.MainButtonCrossword = self._Get("main_button_crossword")
        self.MainButtonTrCard = self._Get("main_button_tr_card")
        self.MainButtonSettings = self._Get("main_button_settings")
        self.MainBack = self._Get("main_back")
        self.WordDetail = self._Get("detail")
        self.WordSave = self._Get("save")
        self.WordEdit = self._Get("edit")
        self.WordExamples = self._Get("word_examples")
        self.Words = self._Get("words")
        self.WordsAll = self._Get("words_all")
        self.WordsWin = self._Get("words_win")
        self.WordsFail = self._Get("words_fail")
        self.WordsSeries = self._Get("words_series")
        self.WordsToLearned = self._Get("words_to_learned")
        self.WordsToIgnore = self._Get("words_to_ignore")
        self.WordsToTraining = self._Get("words_to_training")
        self.WordsNew = self._Get("words_new")
        self.WordsTraining = self._Get("words_in_training")
        self.WordsLearned = self._Get("words_learned")
        self.WordsIgnore = self._Get("words_ignore")
        self.WordsAllWords = self._Get("words_all_words")
        self.WordsRemove = self._Get("words_remove")
        self.BooksTitle = self._Get("books_title")
        self.BooksAuthor = self._Get("books_author")
        self.Crossword = self._Get("crossword")
        self.CrosswordTips = self._Get("crossword_tips")
        self.CrosswordCheck = self._Get("crossword_check")
        self.AddWord = self._Get("add_word")
        self.AddTranscription = self._Get("add_transcription")
        self.AddMeaning = self._Get("add_meaning")
        self.GameHeader = self._Get("game_header")
        self.GameNext = self._Get("game_next")
        self.SettingTranslateTo = self._Get("setting_translate_to")
        self.SettingTranslateFrom = self._Get("setting_translate_from")
        self.SettingTranslatorSwitch = self._Get("setting_translator_switch")
        self.SettingPrincetonSwitch = self._Get("setting_princeton_switch")
        self.AppLanguage = self._Get("app_language")
        self.AppTheme = self._Get("app_theme")

    def _Get(self, key) -> str:
        text = self._GetValueByKey(self._currentLanguage, key, "")
        if not text:
            text = self._GetValueByKey("english", key, "")
        return text
