#:kivy 2.3.0
#:include Data/Screens/UIElements/UnicodeLabel.kv

<FlatButton@Button>:
    defaultButtonColor: app.color.FlatButton
    pressedButtonColor: app.color.FlatButtonPressed
    background_color: self.defaultButtonColor
    background_normal: ''
    background_down: ''
    font_size: 32
    color: app.color.Font
    valign: 'center'
    halign: 'center'
    padding: 5, 5, 5, 5
    font_name: UnicodeFontName
